services:

  navidrome:
    image: deluan/navidrome:latest
    container_name: navi
    restart: unless-stopped
    ports:
      - "8200:4533"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - ND_SCANINTERVAL=1m
      - ND_LOGLEVEL=info
      - ND_PORT=4533
      - ND_TRANSCODINGCACHESIZE=100MB
      - ND_SESSIONTIMEOUT=24h
    volumes:
      - ./data:/data
      - ./music:/music:ro

